import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../services/reports_service.dart';
import '../../services/dashboard_service.dart';
import '../../utils/app_toast.dart';
import '../../widgets/revenue_trend_chart.dart';
import '../../widgets/skeleton_loader.dart';

class ReportsAnalyticsScreen extends StatefulWidget {
  const ReportsAnalyticsScreen({super.key});

  @override
  State<ReportsAnalyticsScreen> createState() => _ReportsAnalyticsScreenState();
}

class _ReportsAnalyticsScreenState extends State<ReportsAnalyticsScreen> {
  final numFormat = NumberFormat('#,##,###');
  final dateFormat = DateFormat('dd/MM/yyyy');

  bool _isLoading = true;
  String _selectedPeriod = 'daily'; // 'daily', 'weekly', 'monthly'

  Map<String, dynamic> _summaryData = {};
  List<dynamic> _trends = [];
  List<dynamic> _paymentBreakdown = [];
  Map<String, dynamic> _dashboardData = {};

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    if (!mounted) return;
    setState(() => _isLoading = true);

    final results = await Future.wait([
      ReportsService.getFinancialSummary(_selectedPeriod),
      DashboardService.getSummary(),
    ]);

    if (mounted) {
      final summary = results[0] as Map<String, dynamic>?;
      final db = results[1] as Map<String, dynamic>?;

      setState(() {
        _summaryData = summary ?? {};
        _trends = (summary?['revenueTrends'] as List<dynamic>?) ?? [];
        _paymentBreakdown = (summary?['paymentBreakdown'] as List<dynamic>?) ?? [];
        _dashboardData = db ?? {};
        _isLoading = false;
      });
    }
  }

  double _getnum(dynamic data, List<String> keys) {
    if (data is! Map) return 0.0;
    for (var key in keys) {
      final keyLower = key.toLowerCase();
      for (var entry in data.entries) {
        if (entry.key.toString().toLowerCase() == keyLower) {
          if (entry.value != null) {
            if (entry.value is num) return (entry.value as num).toDouble();
            return double.tryParse(entry.value.toString()) ?? 0.0;
          }
        }
      }
    }
    return 0.0;
  }

  int _getint(dynamic data, List<String> keys) {
    return _getnum(data, keys).toInt();
  }

  Future<void> _shareWhatsAppReport() async {
    final double revenue = _getnum(_summaryData, ['totalRevenue']);
    final double collections = _getnum(_summaryData, ['totalCollections']);
    final double profit = _getnum(_summaryData, ['grossProfit']);
    final double outstanding = _getnum(_summaryData, ['totalOutstandingReceivables']);
    final double margin = _getnum(_summaryData, ['profitMarginPercentage']);

    String periodTitle = _selectedPeriod == 'weekly'
        ? 'Weekly (Last 8 Weeks)'
        : _selectedPeriod == 'monthly'
            ? 'Monthly (Last 6 Months)'
            : 'Daily (Last 7 Days)';

    final StringBuffer msg = StringBuffer();
    msg.writeln('📊 *RICE BUSINESS - FINANCIAL & REVENUE REPORT* 📊');
    msg.writeln('----------------------------------------');
    msg.writeln('📅 *Period:* $periodTitle');
    msg.writeln('----------------------------------------');
    msg.writeln('💰 *Total Sales Revenue:* ₹${numFormat.format(revenue)}');
    msg.writeln('💵 *Total Collections:* ₹${numFormat.format(collections)}');
    msg.writeln('📈 *Gross Profit:* ₹${numFormat.format(profit)} ($margin%)');
    msg.writeln('📌 *Total Receivables:* ₹${numFormat.format(outstanding)}');
    msg.writeln('----------------------------------------');

    if (_paymentBreakdown.isNotEmpty) {
      msg.writeln('\n💳 *Payment Modes Breakdown:*');
      for (var item in _paymentBreakdown) {
        final mode = item['paymentMode'] ?? 'Cash';
        final total = _getnum(item, ['totalAmount']);
        final pct = _getnum(item, ['percentage']).toStringAsFixed(1);
        msg.writeln('• $mode: ₹${numFormat.format(total)} ($pct%)');
      }
    }

    msg.writeln('\n_Generated by Rice Business Analytics_');

    final encodedText = Uri.encodeComponent(msg.toString());
    final url = Uri.parse('https://wa.me/?text=$encodedText');

    try {
      if (await canLaunchUrl(url)) {
        await launchUrl(url, mode: LaunchMode.externalApplication);
      } else {
        AppToast.showError(context, 'Could not open WhatsApp');
      }
    } catch (e) {
      AppToast.showError(context, 'Error launching WhatsApp: $e');
    }
  }

  Future<void> _exportPdfReport() async {
    final pdf = pw.Document();
    final double revenue = _getnum(_summaryData, ['totalRevenue']);
    final double collections = _getnum(_summaryData, ['totalCollections']);
    final double profit = _getnum(_summaryData, ['grossProfit']);
    final double outstanding = _getnum(_summaryData, ['totalOutstandingReceivables']);
    final double margin = _getnum(_summaryData, ['profitMarginPercentage']);

    String periodTitle = _selectedPeriod == 'weekly'
        ? 'Weekly Analysis'
        : _selectedPeriod == 'monthly'
            ? 'Monthly Analysis'
            : 'Daily Analysis';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('RICE BUSINESS - FINANCIAL ANALYTICS', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800)),
                pw.Text('Date: ${dateFormat.format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            pw.Text('Report Period: $periodTitle', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
            pw.Divider(thickness: 1, color: PdfColors.teal800),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (pw.Context context) {
          return [
            // KPI Grid
            pw.Row(
              children: [
                _pdfKpiCard('Total Revenue', 'Rs. ${numFormat.format(revenue)}', PdfColors.orange800),
                pw.SizedBox(width: 8),
                _pdfKpiCard('Collections', 'Rs. ${numFormat.format(collections)}', PdfColors.green800),
                pw.SizedBox(width: 8),
                _pdfKpiCard('Gross Profit', 'Rs. ${numFormat.format(profit)} ($margin%)', PdfColors.teal800),
                pw.SizedBox(width: 8),
                _pdfKpiCard('Receivables', 'Rs. ${numFormat.format(outstanding)}', PdfColors.red800),
              ],
            ),
            pw.SizedBox(height: 20),

            // Revenue Trends Table
            pw.Text('Revenue & Collection Trends', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 6),
            pw.TableHelper.fromTextArray(
              headers: ['Interval', 'Sales Revenue', 'Payments Collected', 'Estimated Profit', 'Sales Count'],
              data: _trends.map((t) {
                final label = t['label'] ?? '';
                final sAmt = _getnum(t, ['salesAmount']);
                final pAmt = _getnum(t, ['paymentAmount']);
                final prAmt = _getnum(t, ['profitAmount']);
                final count = _getint(t, ['salesCount']);

                return [
                  label,
                  'Rs. ${numFormat.format(sAmt)}',
                  'Rs. ${numFormat.format(pAmt)}',
                  'Rs. ${numFormat.format(prAmt)}',
                  '$count',
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 9),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal700),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                1: pw.Alignment.centerRight,
                2: pw.Alignment.centerRight,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.center,
              },
            ),
            pw.SizedBox(height: 20),

            // Payment Breakdown Table
            if (_paymentBreakdown.isNotEmpty) ...[
              pw.Text('Payment Modes Distribution', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.TableHelper.fromTextArray(
                headers: ['Payment Mode', 'Total Collection', 'Transactions', 'Share (%)'],
                data: _paymentBreakdown.map((b) {
                  final mode = b['paymentMode'] ?? 'Cash';
                  final amt = _getnum(b, ['totalAmount']);
                  final count = _getint(b, ['transactionCount']);
                  final pct = _getnum(b, ['percentage']).toStringAsFixed(1);

                  return [
                    mode,
                    'Rs. ${numFormat.format(amt)}',
                    '$count',
                    '$pct %',
                  ];
                }).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 9),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.teal700),
                cellStyle: const pw.TextStyle(fontSize: 9),
              ),
            ],
          ];
        },
        footer: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Divider(thickness: 0.5, color: PdfColors.grey400),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Rice Business Analytics System', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              ],
            ),
          ],
        ),
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Financial_Analytics_Report_${_selectedPeriod}.pdf',
    );
  }

  pw.Widget _pdfKpiCard(String title, String value, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(8),
        decoration: pw.BoxDecoration(
          color: PdfColors.grey100,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          border: pw.Border.all(color: PdfColors.grey300),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(title, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
            pw.SizedBox(height: 4),
            pw.Text(value, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: color)),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final isDark = theme.brightness == Brightness.dark;

    final double totalRevenue = _getnum(_summaryData, ['totalRevenue']);
    final double totalCollections = _getnum(_summaryData, ['totalCollections']);
    final double grossProfit = _getnum(_summaryData, ['grossProfit']);
    final double totalReceivables = _getnum(_summaryData, ['totalOutstandingReceivables']);
    final double profitMargin = _getnum(_summaryData, ['profitMarginPercentage']);

    final topProducts = (_dashboardData['topSellingProducts'] as List<dynamic>?) ?? [];

    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Container(
        decoration: BoxDecoration(
          color: isDark ? null : theme.scaffoldBackgroundColor,
          gradient: isDark
              ? RadialGradient(
                  center: const Alignment(0, -0.6),
                  radius: 1.2,
                  colors: [
                    colorScheme.surface,
                    theme.primaryColor,
                    Colors.black,
                  ],
                  stops: const [0.0, 0.6, 1.0],
                )
              : null,
        ),
        child: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Top Bar
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Row(
                  children: [
                    GestureDetector(
                      onTap: () => Navigator.pop(context),
                      child: Icon(Icons.arrow_back, color: colorScheme.primary),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Text(
                        'Visual Analytics & Reports',
                        style: TextStyle(
                          color: colorScheme.onSurface,
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.picture_as_pdf_outlined),
                      color: colorScheme.primary,
                      tooltip: 'Export PDF Report',
                      onPressed: _exportPdfReport,
                    ),
                    IconButton(
                      icon: const Icon(Icons.share_outlined),
                      color: Colors.green,
                      tooltip: 'Share on WhatsApp',
                      onPressed: _shareWhatsAppReport,
                    ),
                  ],
                ),
              ),

              // Period Filter Switcher Bar
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: [
                    _buildPeriodChip('Daily (Last 7 Days)', 'daily'),
                    const SizedBox(width: 8),
                    _buildPeriodChip('Weekly (8 Weeks)', 'weekly'),
                    const SizedBox(width: 8),
                    _buildPeriodChip('Monthly (6 Mos)', 'monthly'),
                  ],
                ),
              ),
              const SizedBox(height: 14),

              Expanded(
                child: _isLoading
                    ? ListSkeleton(title: 'Loading Financial Analytics...')
                    : RefreshIndicator(
                        onRefresh: _loadData,
                        child: SingleChildScrollView(
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          physics: const AlwaysScrollableScrollPhysics(),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              // 4 KPI Cards Grid
                              Row(
                                children: [
                                  Expanded(
                                    child: _buildKpiCard(
                                      'Gross Revenue',
                                      '₹${numFormat.format(totalRevenue)}',
                                      Icons.trending_up_rounded,
                                      Colors.orangeAccent,
                                      isDark,
                                    ),
                                  ),
                                  const SizedBox(width: 10),
                                  Expanded(
                                    child: _buildKpiCard(
                                      'Collections',
                                      '₹${numFormat.format(totalCollections)}',
                                      Icons.payments_rounded,
                                      Colors.green,
                                      isDark,
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 10),
                              Row(
                                children: [
                                  Expanded(
                                    child: _buildKpiCard(
                                      'Gross Profit',
                                      '₹${numFormat.format(grossProfit)} ($profitMargin%)',
                                      Icons.savings_rounded,
                                      colorScheme.primary,
                                      isDark,
                                    ),
                                  ),
                                  const SizedBox(width: 10),
                                  Expanded(
                                    child: _buildKpiCard(
                                      'Total Receivables',
                                      '₹${numFormat.format(totalReceivables)}',
                                      Icons.account_balance_outlined,
                                      Colors.redAccent,
                                      isDark,
                                    ),
                                  ),
                                ],
                              ),
                              const SizedBox(height: 20),

                              // Interactive Revenue Trend Chart Card
                              Container(
                                padding: const EdgeInsets.all(16),
                                decoration: BoxDecoration(
                                  color: isDark ? theme.primaryColor.withValues(alpha: 0.4) : colorScheme.surface,
                                  borderRadius: BorderRadius.circular(16),
                                  border: Border.all(
                                    color: colorScheme.onSurface.withValues(alpha: 0.08),
                                  ),
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Row(
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      children: [
                                        Text(
                                          'Revenue & Collection Trends',
                                          style: TextStyle(
                                            color: colorScheme.onSurface,
                                            fontSize: 16,
                                            fontWeight: FontWeight.bold,
                                          ),
                                        ),
                                        Icon(Icons.bar_chart_rounded, color: colorScheme.primary),
                                      ],
                                    ),
                                    const SizedBox(height: 16),
                                    RevenueTrendChart(
                                      trends: _trends,
                                      period: _selectedPeriod,
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(height: 20),

                              // Payment Mode Breakdown
                              if (_paymentBreakdown.isNotEmpty) ...[
                                Text(
                                  'Payment Modes Distribution',
                                  style: TextStyle(
                                    color: colorScheme.onSurface,
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 10),
                                ..._paymentBreakdown.map((item) {
                                  final mode = item['paymentMode'] ?? 'Cash';
                                  final double amt = _getnum(item, ['totalAmount']);
                                  final double pct = _getnum(item, ['percentage']);
                                  final int count = _getint(item, ['transactionCount']);

                                  return Container(
                                    margin: const EdgeInsets.only(bottom: 8),
                                    padding: const EdgeInsets.all(12),
                                    decoration: BoxDecoration(
                                      color: isDark ? theme.primaryColor.withValues(alpha: 0.35) : colorScheme.surface,
                                      borderRadius: BorderRadius.circular(12),
                                      border: Border.all(
                                        color: colorScheme.onSurface.withValues(alpha: 0.08),
                                      ),
                                    ),
                                    child: Column(
                                      children: [
                                        Row(
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          children: [
                                            Row(
                                              children: [
                                                Icon(
                                                  mode.toString().toLowerCase().contains('online') || mode.toString().toLowerCase().contains('upi')
                                                      ? Icons.qr_code_scanner_rounded
                                                      : Icons.money_rounded,
                                                  color: colorScheme.primary,
                                                  size: 18,
                                                ),
                                                const SizedBox(width: 8),
                                                Text(
                                                  mode,
                                                  style: TextStyle(
                                                    color: colorScheme.onSurface,
                                                    fontWeight: FontWeight.bold,
                                                  ),
                                                ),
                                                const SizedBox(width: 6),
                                                Text(
                                                  '($count txns)',
                                                  style: TextStyle(color: colorScheme.outline, fontSize: 11),
                                                ),
                                              ],
                                            ),
                                            Text(
                                              '₹${numFormat.format(amt)} (${pct.toStringAsFixed(1)}%)',
                                              style: TextStyle(
                                                color: colorScheme.primary,
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                          ],
                                        ),
                                        const SizedBox(height: 8),
                                        ClipRRect(
                                          borderRadius: BorderRadius.circular(4),
                                          child: LinearProgressIndicator(
                                            value: (pct / 100.0).clamp(0.0, 1.0),
                                            minHeight: 6,
                                            backgroundColor: colorScheme.onSurface.withValues(alpha: 0.1),
                                            valueColor: AlwaysStoppedAnimation<Color>(colorScheme.primary),
                                          ),
                                        ),
                                      ],
                                    ),
                                  );
                                }),
                                const SizedBox(height: 20),
                              ],

                              // Top Products Breakdown
                              if (topProducts.isNotEmpty) ...[
                                Text(
                                  'Top Selling Rice Varieties (Last 30 Days)',
                                  style: TextStyle(
                                    color: colorScheme.onSurface,
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 10),
                                ...topProducts.map((p) {
                                  final name = p['productName'] ?? 'Product';
                                  final brand = p['brandName'] ?? '';
                                  final double qty = _getnum(p, ['totalQuantitySold']);
                                  final double totalSales = _getnum(p, ['totalSalesAmount']);

                                  return Container(
                                    margin: const EdgeInsets.only(bottom: 8),
                                    padding: const EdgeInsets.all(12),
                                    decoration: BoxDecoration(
                                      color: isDark ? theme.primaryColor.withValues(alpha: 0.35) : colorScheme.surface,
                                      borderRadius: BorderRadius.circular(12),
                                      border: Border.all(
                                        color: colorScheme.onSurface.withValues(alpha: 0.08),
                                      ),
                                    ),
                                    child: Row(
                                      children: [
                                        Container(
                                          padding: const EdgeInsets.all(8),
                                          decoration: BoxDecoration(
                                            color: Colors.amber.withValues(alpha: 0.15),
                                            shape: BoxShape.circle,
                                          ),
                                          child: const Icon(Icons.rice_bowl_rounded, color: Colors.amber, size: 18),
                                        ),
                                        const SizedBox(width: 12),
                                        Expanded(
                                          child: Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                '$name ($brand)',
                                                style: TextStyle(
                                                  color: colorScheme.onSurface,
                                                  fontWeight: FontWeight.bold,
                                                  fontSize: 13,
                                                ),
                                              ),
                                              Text(
                                                '$qty Bags Sold',
                                                style: TextStyle(color: colorScheme.outline, fontSize: 11),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Text(
                                          '₹${numFormat.format(totalSales)}',
                                          style: TextStyle(
                                            color: colorScheme.primary,
                                            fontWeight: FontWeight.bold,
                                          ),
                                        ),
                                      ],
                                    ),
                                  );
                                }),
                              ],
                              const SizedBox(height: 30),
                            ],
                          ),
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildPeriodChip(String label, String value) {
    final colorScheme = Theme.of(context).colorScheme;
    final isSelected = _selectedPeriod == value;

    return ChoiceChip(
      label: Text(
        label,
        style: TextStyle(
          fontSize: 12,
          color: isSelected ? colorScheme.onPrimary : colorScheme.onSurface,
        ),
      ),
      selected: isSelected,
      selectedColor: colorScheme.primary,
      onSelected: (selected) {
        if (selected) {
          setState(() {
            _selectedPeriod = value;
          });
          _loadData();
        }
      },
    );
  }

  Widget _buildKpiCard(String title, String value, IconData icon, Color color, bool isDark) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isDark ? theme.primaryColor.withValues(alpha: 0.4) : colorScheme.surface,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: colorScheme.onSurface.withValues(alpha: 0.08),
        ),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.15),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(icon, color: color, size: 20),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: TextStyle(
                    fontSize: 11,
                    color: colorScheme.outline,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 2),
                Text(
                  value,
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    color: color,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
